name: cs_wownero_flutter_libs_android_arm64_v8a
description: "Android arm64-v8a bins for cs_wownero_flutter_libs"
version: 1.2.0
repository: https://github.com/cypherstack/cs_wownero
homepage: https://github.com/cypherstack/cs_wownero
issue_tracker: https://github.com/cypherstack/cs_wownero/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.cypherstack.cs_wownero_flutter_libs_android_arm64_v8a
        pluginClass: CsWowneroFlutterLibsAndroidArm64V8aPlugin
                                      