name: cs_wownero_flutter_libs_ios
description: Ios implementation of cs_wownero_flutter_libs
version: 1.2.1
repository: https://github.com/cypherstack/cs_wownero
homepage: https://github.com/cypherstack/cs_wownero
issue_tracker: https://github.com/cypherstack/cs_wownero/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cs_wownero_flutter_libs_platform_interface: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CsWowneroFlutterLibsIosPlugin
        dartPluginClass: CsWowneroFlutterLibsIos
